services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80" # Открываем порт 80 для HTTP
      - "443:443"  # Открываем порт 443 для HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Подключаем конфигурацию Nginx
      - ./letsencrypt:/etc/letsencrypt  # Сертификаты Let's Encrypt
      - ./html:/usr/share/nginx/html  # Временные файлы для Certbot
    depends_on:
      - diary # Указываем, что Nginx должен дождаться запуска вашего приложения
    networks:
      - my_network
  diary:
    build:
      context: .
      dockerfile: diary/Dockerfile 
    container_name: dotnet_app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__applicationDbContextConnection=Host=db;Database=interactiveboardentities;Username=postgres;Password=228228228
      - ConnectionStrings__diaryDbContextConnection=Host=db;Database=diaryentities;Username=postgres;Password=228228228
      - ConnectionStrings__DiaryIdentityDbContextConnection=Host=db;Database=diaryidentity;Username=postgres;Password=228228228
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    networks:
      - my_network

networks:
  my_network:
    external: true
