services:
  diary:
    environment:
      - ASPNETCORE_HTTPS_PORTS=8081  
    expose:
      - "8081"  # Порт доступен только внутри Docker
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro  