services:
  diary:
    environment:
      - ASPNETCORE_HTTPS_PORTS=8081  
    ports:
<<<<<<< HEAD
      - "8081:8081"  
=======
      - "8080:8080"
      - "8081:8081"
>>>>>>> 4bae6fef3638e403f1d017b22ce6b669759087b8
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro  