services:
  diary:
    build:
      context: .
      dockerfile: diary/Dockerfile
    container_name: diary_api           
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081   # внутри контейнера
      - ConnectionStrings__applicationDbContextConnection=Host=db;Database=interactiveboardentities;Username=postgres;Password=228228228
      - ConnectionStrings__diaryDbContextConnection=Host=db;Database=diaryentities;Username=postgres;Password=228228228
      - ConnectionStrings__DiaryIdentityDbContextConnection=Host=db;Database=diaryidentity;Username=postgres;Password=228228228
    volumes:
      - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      - db
    expose:                              # порт доступен только другим сервисам Compose
      - "8081"
    networks:
      - shared_db_net

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 228228228
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - shared_db_net
    restart: always

  # --- обратный прокси + SSL (коротко) ------------------
  nginx:
    image: nginx:alpine
    container_name: reverse_proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - diary
    networks:
      - shared_db_net

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: >
      certonly --webroot --webroot-path=/var/www/certbot
      --email admin@fdit-diary.ru --agree-tos --no-eff-email
      -d fdit-diary.ru -d www.fdit-diary.ru
    networks:
      - shared_db_net
# --------------------------------------------------------

networks:
  shared_db_net:
    external: true

volumes:
  postgres_data:
  certbot-etc:
  certbot-var:
